#!/usr/bin/env bash
# Optional WSL-only setup. Run after .bin/install.sh.
#
# Generates ~/.config/zsh/wsl.zshrc, which adds a few Windows-side tools to
# $PATH for distros with appendWindowsPath = false in /etc/wsl.conf, and
# defines itrc / itr to check and restore WSL interop.
# ~/.zshrc sources every ~/.config/zsh/*.zshrc, so nothing else is needed.
set -ue

DEFAULT_WIN_USER="mercu"

helpmsg() {
	cat <<EOF
Usage: $0 [-u|--user <windows-username>] [--help|-h]

  -u, --user   Windows user name under C:\\Users (default: $DEFAULT_WIN_USER)
               Can also be given via the WIN_USER environment variable.
EOF
}

WIN_USER="${WIN_USER:-$DEFAULT_WIN_USER}"

while [ $# -gt 0 ]; do
	case "$1" in
		-u | --user)
			[ $# -ge 2 ] || { echo "Error: $1 requires an argument" >&2; helpmsg >&2; exit 1; }
			WIN_USER="$2"
			shift
			;;
		--help | -h)
			helpmsg
			exit 0
			;;
		*)
			echo "Error: unknown option: $1" >&2
			helpmsg >&2
			exit 1
			;;
	esac
	shift
done

is_wsl() {
	[ -n "${WSL_DISTRO_NAME:-}" ] && return 0
	[ -f /proc/version ] && grep -qi microsoft /proc/version && return 0
	return 1
}

if ! is_wsl; then
	echo "Error: this script is for WSL only" >&2
	exit 1
fi

WIN_USER_HOME="/mnt/c/Users/$WIN_USER"
if [ ! -d "$WIN_USER_HOME" ]; then
	echo "Warning: $WIN_USER_HOME does not exist; check the Windows user name (-u)" >&2
fi

DEST_DIR="$HOME/.config/zsh"
DEST="$DEST_DIR/wsl.zshrc"
mkdir -p "$DEST_DIR"

# Drop a stale symlink so we write a regular file.
[ -L "$DEST" ] && rm -f "$DEST"

{
	cat <<'EOF'
# WSL-specific zsh configuration.
# Generated by ~/dotfiles/.bin/wsl.sh; re-run it to regenerate.
#
# This assumes appendWindowsPath = false in /etc/wsl.conf, so the Windows PATH
# is not inherited. Add just the Windows-side tools we want to call from WSL.

EOF
	printf 'WIN_USER_HOME=%q\n' "$WIN_USER_HOME"
	cat <<'EOF'

# zed          : $WIN_USER_HOME/AppData/Local/Programs/Zed/bin/zed
# code         : $WIN_USER_HOME/AppData/Local/Programs/Microsoft VS Code/bin/code
# explorer.exe : /mnt/c/Windows/explorer.exe
wsl_path_dirs=(
    "$WIN_USER_HOME/AppData/Local/Programs/Zed/bin"
    "$WIN_USER_HOME/AppData/Local/Programs/Microsoft VS Code/bin"
    "/mnt/c/Windows"
)

for dir in "${wsl_path_dirs[@]}"; do
    if [ -d "$dir" ]; then
        path+=("$dir")
    fi
done
unset dir wsl_path_dirs

# WSL interop (running Windows .exe from WSL) sometimes gets unregistered.
# itrc : show the current state of the WSLInterop binfmt entry
# itr  : re-register it (requires sudo)
itrc() {
    cat /proc/sys/fs/binfmt_misc/WSLInterop 2>&1
}
itr() {
    sudo sh -c 'echo ":WSLInterop:M::MZ::/init:PF" > /proc/sys/fs/binfmt_misc/register'
}
EOF
} > "$DEST"

echo "Generated: $DEST (Windows user: $WIN_USER)"
echo "Open a new shell or run 'exec zsh' to apply."
